# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Auto Gradle Package

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Patch and build
      run: |
        chmod 777 gradlew
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        ./gradlew applyPatches --stacktrace
        ./gradlew createReobfBundlerJar --stacktrace
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SkydomIslandManager Artifact
        path: build/libs/islet-bundler-*-SNAPSHOT-reobf.jar