# This is a basic workflow to help you get started with Actions

name: Auto ApplyPatches

# Controls when the workflow will run
on: [push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        # Only run on PRs if the source branch is on someone else's repo
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
                java-version: 17
            - name: Patch and Build
              run: |
                  ./gradlew applyPatches --stacktrace
                  ./gradlew createReobfBundlerJar --stacktrace
            - uses: actions/upload-artifact@v3
              with:
                name: Skydom-Server Artifact
                path: build/libs/*.jar
